name: master-deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: robinfc/cloud:latest

      - name: SSH into Tencent Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            docker stop nginx-container || true
            docker rm nginx-container || true
            docker pull robinfc/cloud:latest
            docker run -d -p 80:80 \
              -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
              -v /etc/nginx/robin-fc.cloud_bundle.crt:/etc/nginx/robin-fc.cloud_bundle.crt \
              -v /etc/nginx/robin-fc.cloud.key:/etc/nginx/robin-fc.cloud.key \
              --name nginx-container robinfc/cloud:latest
